### ISSUE TITLE
no data received when the PC is connected to WIFI

### ISSUE THREAD

**Issue by xiaoshan-lin** [IMRCLab/motion_capture_tracking#11]
We use this package ([with the official SDK](https://github.com/whoenig/NatNetSDKCrossplatform/issues/3#issuecomment-954907842)) to get data from Optitrack. Everything works fine when the PC is only connected to ethernet. But it shows "no data received" when the PC is connected to WIFI and ethernet. We ran ./sampleclient 192.168.1.133 in the [NatNetSDKCrossplatform](https://github.com/whoenig/NatNetSDKCrossplatform) package and were able to receive raw data from optitrack. Running ./packetsamplecilent 192.168.1.133 doesn't output anything except the package version.

Do you have any idea about why this package couldn't receive data when the PC is connected to WIFI?

Thank you!

**Comment by whoenig** [comment]
Any reason why you don't just use the official SDK backend?

**Comment by xiaoshan-lin** [comment]
We are indeed using the official SDK. Connecting the PC to the WIFI router with an ethernet cable solves this issue. I will close the issue here. Thank you!
