### ISSUE TITLE
Mocap type ：NOKOV, Unknown motion capture type

### ISSUE THREAD

**Issue by Omikaa** [IMRCLab/motion_capture_tracking#12]
Hello, thank you for your time.
I followed the motion_capture_tracking/deps/libmotioncapture/README.md, and i can succed to run python.py in the folder named examples to get the mocap data.
After that ,i colcon build the mocap tracking package.
But I modified the cfg.yaml in motion_capture_tracking/config like below:
/motion_capture_tracking:
  ros__parameters:
    # one of "optitrack", "optitrack_closed_source", "vicon", "qualisys", "nokov", "vrpn", "motionanalysis"
    type: "nokov"
    # Specify the hostname or IP of the computer running the motion capture software
    hostname: "192.168.50.12"

    # Use "motionCapture" to disable custom rigid body tracking (to rely on the vendor's software)
    # Use "libRigidBodyTracker" for custom frame-by-frame tracking, in which you need to define 
    #                           marker_configurations, dynamics_configurations, and rigid_bodies below.
    mode: "motionCapture"

Then, i ran launch.py and got unknown motion capture type:
[INFO] [launch]: All log files can be found below /home/omika/.ros/log/2024-01-10-21-20-33-665293-omika-OMEN-by-HP-Laptop-15-dc1xxx-91842
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [motion_capture_tracking_node-1]: process started with pid [91844]
[INFO] [rviz2-2]: process started with pid [91846]
[motion_capture_tracking_node-1] logClouds=0
[motion_capture_tracking_node-1] terminate called after throwing an instance of 'std::runtime_error'
[motion_capture_tracking_node-1]   what():  Unknown motion capture type!
[ERROR] [motion_capture_tracking_node-1]: process has died [pid 91844, exit code -6, cmd '/home/omika/ros2_ws_crazyswarm2/install/motion_capture_tracking/lib/motion_capture_tracking/motion_capture_tracking_node --ros-args -r __node:=motion_capture_tracking --params-file /home/omika/ros2_ws_crazyswarm2/install/motion_capture_tracking/share/motion_capture_tracking/config/cfg.yaml'].
[rviz2-2] [INFO] [1704892834.436109196] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1704892834.436216902] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-2] [INFO] [1704892834.477423896] [rviz2]: Stereo is NOT SUPPORTED
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[rviz2-2] [INFO] [1704892836.868855744] [rclcpp]: signal_handler(signal_value=2)
[rviz2-2] QFileSystemWatcher::removePaths: list is empty
[rviz2-2] QFileSystemWatcher::removePaths: list is empty
[INFO] [rviz2-2]: process has finished cleanly [pid 91846]

please help me find the problem.

**Comment by whoenig** [comment]
NOKOV does not have a public SDK. You need to manually add the SDK, see https://github.com/IMRCLab/libmotioncapture/tree/5e892e8a3402d1753a02c384738d6dd2c94c8417#compile-options for a description.

**Comment by Omikaa** [comment]
![2024-01-11_08-39](https://github.com/IMRCLab/motion_capture_tracking/assets/136170290/a650d008-d0b1-4b53-87eb-cb70fe99521f)
![2024-01-11_08-41](https://github.com/IMRCLab/motion_capture_tracking/assets/136170290/eb3d8a5c-a06f-4d9d-a4ce-ac13cd4a94e3)
i have added the SDK ,and run the example, but i failed to run the mocap tracking launch.py because of unkown mocap type.

**Comment by whoenig** [comment]
Did you enable it in the compiler settings? (see https://github.com/IMRCLab/libmotioncapture/blob/5e892e8a3402d1753a02c384738d6dd2c94c8417/CMakeLists.txt#L10). Please report back here once it works with the steps taken, so I can update the readme in this repository to make the steps explicit and easier to find.

**Comment by Omikaa** [comment]
yes,i have enabled it in the CMakelists.txt before, but it is still failed to run launch.py.
![image](https://github.com/IMRCLab/motion_capture_tracking/assets/136170290/1d8a3640-137c-4afe-a582-78828d065cf1)

**Comment by whoenig** [comment]
Did you colcon build after changing and did the build actually succeed?

**Comment by Omikaa** [comment]
i had colcon build it, still not work .there is the log:Starting >>> crazyflie_interfaces                                                                                                                                            
Starting >>> motion_capture_tracking_interfaces    
Finished <<< motion_capture_tracking_interfaces [0.91s]                                                                        
Starting >>> motion_capture_tracking
Finished <<< crazyflie_interfaces [1.97s]                                                                         
Starting >>> crazyflie_py
Starting >>> crazyflie                                                                          
Starting >>> crazyflie_sim                                                                                         
Finished <<< motion_capture_tracking [1.59s]                                                                                              
Finished <<< crazyflie [1.30s]                                                                                    
--- stderr: crazyflie_sim                                                             
/home/omika/anaconda3/envs/crazyswarm2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
---
Finished <<< crazyflie_sim [1.61s]
Finished <<< crazyflie_py [2.10s]          
Starting >>> crazyflie_examples
--- stderr: crazyflie_examples                           
/home/omika/anaconda3/envs/crazyswarm2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
---
Finished <<< crazyflie_examples [0.90s]

Summary: 7 packages finished [7.38s]
  2 packages had stderr output: crazyflie_examples crazyflie_sim

**Comment by whoenig** [comment]
The build succeeded (what you get are warnings). If you can provide me with the SDK (contact info at https://github.com/IMRCLab/motion_capture_tracking/blob/ros2/motion_capture_tracking/package.xml#L7), I can take a look. The code was contributed by a third party, so I have not tried it myself.

**Comment by Omikaa** [comment]
[nokov_sdk_2.5.2875.zip](https://github.com/IMRCLab/motion_capture_tracking/files/13925218/nokov_sdk_2.5.2875.zip)
this is the nokov sdk.Please take a look.

**Comment by whoenig** [comment]
I tried it and added some documentation at https://github.com/IMRCLab/motion_capture_tracking#nokov-vendor-specific-instructions. Make sure you pull beforehand, since I also changed one of the build files. I verified that after the change I can use "nokov" and that I get a reasonable error ("Error connecting XINGYING on address: ... Code:1"), given that I do not have a NOKOV Mocap to test with.

**Comment by Omikaa** [comment]
Thanks, I did the same thing like you. Pull the SDK into deps files , modify the CMakeLists.txt and run colcon build. What change did you do in the build files?

**Comment by whoenig** [comment]
https://github.com/IMRCLab/motion_capture_tracking/commit/1237e824efd00a5347e90059c3dfe4b090d0a44a

I changed a different CMakeLists.txt

**Comment by Omikaa** [comment]
Thanks, after I changed the file, I can connect with nokov.
