### ISSUE TITLE
Tracking the twist

### ISSUE THREAD

**Issue by Omikaa** [IMRCLab/motion_capture_tracking#16]
Hello, I am using the "NOKOV" Mocap to track crazyflies.
Now I want to control the cf with python API , and I've seen the example that is 
'crazyflie-lib-python/examples/mocap/mocap_hl_commander.py'. 
However, in that example, I can only get 'pose' from mocap. Are there any possibilities to get the Mocap's twist topic with motion_capture_tracking? If possible, how can I log twist in the mocap thread?
Thank you, and wish for rapid reply!!!
[https://github.com/bitcraze/crazyflie-lib-python/blob/master/examples/mocap/mocap_hl_commander.py](url)

**Comment by whoenig** [comment]
Not entirely sure what you mean by twist, but you do get both position and orientation, see https://github.com/bitcraze/crazyflie-lib-python/blob/a77b4023867c27d814c6820373ec2a7d158a2ef5/examples/mocap/mocap_hl_commander.py#L104-L105.

**Comment by Omikaa** [comment]
Yes，I know that. 
What I mean are the linear velocity and angular velocity of a quadrotor. Nokov mocap can publish a topic that includes the linear velocity and angular velocity.So I want to know if I can get those in mocap_hl_commander.py.

**Comment by whoenig** [comment]
No, that is currently not possible. You could estimate it yourself numerically.

**Comment by Omikaa** [comment]
OK，Thanks for your reply.
