### ISSUE TITLE
No Data from motioncapture

### ISSUE THREAD

**Issue by JasonTStanley** [IMRCLab/motion_capture_tracking#21]
Im using Optitrack with motive 3.1 I am not able to get any data from motive. I get no output and I'm not sure where to start debugging? I have run the examples from https://github.com/IMRCLab/libmotioncapture but they don't work (the c++ just segfaults immediately and the python example hangs on waiting for data)

I have also tested NatNetSDKCrossplatform and the 3 example scripts from there, all which behave differently. 
Sample client:
![image](https://github.com/user-attachments/assets/9ffa76cc-456b-4494-984e-dae30be14b38)
Seems to work then hangs here.

running ` ./minimalClient`
gives `Unable to connect to server.  Error code: 3. Exiting. `
and 
`./packetClient 192.168.0.108`
gives the following, then hangs and doesn't continue. 
![image](https://github.com/user-attachments/assets/c0262ba3-de1f-4a8b-b078-9f094bcc904e)

Im running on Ubuntu 22.04 with ros2 humble. Any help is appreciated thank you.

**Comment by whoenig** [comment]
Which backend are you using? For Motive 3.1, we use "optitrack_closed_source", rather than "optitrack", because of the segfault that we haven't investigated yet (although there was recently a PR that we merged that was supposed to fix that).

**Comment by JasonTStanley** [comment]
Thank you for the clarification. I was testing with both "optitrack" and "optitrack_closed_source" Im realizing now that the branch I had was checking out a submodule with an old branch of libmotioncapture and therefore NatNetSDKCrossplatform as well, and it was only supported up to the NatNetSDK 4.0 , i am updating the repos to be on latest main (I see the PR you mentinoed and I am checking that I will use that.) I will test with Optitrack later today and let you know if I am still having issues. 

Thank you again!

**Comment by JasonTStanley** [comment]
Hello again! I have tested a few more things and come to the conclusion that this is a bug in NatNetSDK on my version of linux. I am using WSL and there seems to be some problem with how the NatNetSDK works on this environment. Recreating it on native linux and everything works perfectly. I'm new to uisng optitrack and this hardware so I apoligize for making the issue in the wrong project. I apreciate you taking the time to respond. Have a great day!
