### ISSUE TITLE
unknown rigid body exception

### ISSUE THREAD

**Issue by marios-stam** [IMRCLab/motion_capture_tracking#6]
I am using this software having vicon in tracking mode. Although everything works fine (I get the position of the object I have selected to track in vicon)  after losing track of it  for a moment I get the error "Unknown rigid body!". 

It makes sense, since from what I understand it constantly tries to track the object. 
Is there a way to remove this exception  though, since in my use case I am losing track of the object quite a lot? (I am trying to track a ball which is usually falling on the ground).

Thank you in advance!

**Comment by whoenig** [comment]
This is already fixed in https://github.com/IMRCLab/libmotioncapture/pull/10, but so far nobody was able to confirm that it works (I don't have access to a VICON system.)

**Comment by marios-stam** [comment]
Oh seems that I have missed this pull request, I am going to test it soon then and I will let you know of the outcome. 
Thank you!

**Comment by whoenig** [comment]
I merged the PR and also updated the submodule here. Thanks for your help!
